FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["../Contracts/CSCourse.Contracts.csproj", "Contracts/"]
COPY ["Presentation/Events.Service.csproj", "Events.Service/Presentation/"]
COPY ["Application/Events.Service.Application.csproj", "Events.Service/Application/"]
COPY ["Domain/Events.Service.Domain.csproj", "Events.Service/Domain/"]
COPY ["Infrastructure/Events.Service.Infrastructure.csproj", "Events.Service/Infrastructure/"]

RUN dotnet restore "Events.Service/Presentation/Events.Service.csproj"

COPY . .
WORKDIR "/src/Events.Service/Presentation"
RUN dotnet publish "Events.Service.Presentation.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Events.Service.Presentation.dll"]
