{
 "title": "INFO - Сервис бронирования",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latency (p50, p95, p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(http_server_request_duration_seconds_bucket{http_route!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_server_request_duration_seconds_bucket{http_route!=\"/metrics\"}[$__rate_interval]))\n\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_server_request_duration_seconds_bucket{http_route!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests (currently processing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "{{handler}}" }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}